export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const FILE_SUBMIT_SUCCESS = "FILE_SUBMIT_SUCCESS";

export const TOGGLE_SUBMIT_BUTTON = "TOGGLE_SUBMIT_BUTTON";
export const ENABLE_SUBMIT_BUTTON = "ENABLE_SUBMIT_BUTTON";
export const DISABLE_SUBMIT_BUTTON = "DISABLE_SUBMIT_BUTTON";
